---
apiVersion: v1
kind: Service
metadata:
  name: s2i-ereminder-web
  labels:
    app: angular
spec:
  ports:
    - port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    app: angular
    tier: web
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: s2i-ereminder-web
  labels:
    app: angular
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: angular
        tier: web
    spec:
      containers:
        - image: garydhub1/s2i_ereminder_front:dev
          imagePullPolicy: IfNotPresent
          name: s2i-ereminder-web
          env:
            - name: LOG_LEVEL
              value: info
          ports:
            - containerPort: 8081
