apiVersion: v1
kind: Service
metadata:
  name: {{ template "s2i-ereminder-web.fullname" . }}
  labels:
    app: {{ template "s2i-ereminder-web.name" . }}
    chart: {{ template "s2i-ereminder-web.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetport }}
      protocol: {{ .Values.service.portprotocol }}
      name: {{ .Values.service.portname }}
  selector:
    app: {{ template "s2i-ereminder-web.name" . }}
    release: {{ .Release.Name }}
